### ISSUE TITLE
Wrong weight

### ISSUE THREAD

**Issue by Schnuecks** [AndreasReitberger/3D-Print-Cost-Calculator-App#3]
**Describe the bug**
The weight from files loaded via octoprint has wrong weight.

**To Reproduce**
1. Go to files
2. Open via octoprint 
3. Select file 
4. Every file has weight -1

**Expected behavior**
The correct value should be there unless calculations are completely useless.

**Screenshots**
![image](https://user-images.githubusercontent.com/27301329/147012271-25db3728-5585-4178-9016-70ac88aecd85.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone13 Pro
 - OS: iOS 15.2
 - Version 1.2.6

**Comment by AndreasReitberger** [comment]
Hi,
this is actually not a bug. The app fetches only the volume from OctoPrint.
Later, when the app calculates the print cost it uses the density of the select material and calculates the weight out of the model volume.

This ensures that the material costs are accurate. Otherwise, if the material is sliced with PLA and you select ABS as material, the weight in PLA would be more as with ABS. So the material costs would be a little off.

Hope this helps understanding the calculation process.

P.S. the desktop tool does it the same way 👍🏻

Best,
Andreas
